image: docker:stable

services:
  - docker:dind

before_script:
  - echo "logging into dockerhub"
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - echo "login successfully"

build-backend:
  stage: build
  script:
    - echo "building backend image"
    - docker build -f ./backend/Dockerfile -t $CI_REGISTRY_USER/workshop-ci-entrega-02-backend:latest ./backend
    - echo "pushing backend image"
    - docker push "$CI_REGISTRY_USER/workshop-ci-entrega-02-backend:latest"
    - echo "build and push were successful"

build-frontend:
  stage: build
  script:
    - echo "building frontend image"
    - docker build -f ./frontend/Dockerfile -t $CI_REGISTRY_USER/workshop-ci-entrega-02-frontend:latest ./frontend
    - echo "pushing frontend image"
    - docker push "$CI_REGISTRY_USER/workshop-ci-entrega-02-frontend:latest"
    - echo "build and push were successful"