image: docker:stable

services:
  - docker:dind

before_script:
  - echo "logging into dockerhub"
  - echo "$CI_REGISTRY_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
  - echo "login successfully"

build-backend:
  stage: build
  script:
    - echo "building backend image"
    - docker build -f ./backend/Dockerfile -t $CI_REGISTRY_USER/workshop-ci-entrega-02-backend:latest ./backend
    - echo "pushing backend image"
    - docker push "$CI_REGISTRY_USER/workshop-ci-entrega-02-backend:latest"
    - echo "build and push were successful"