image: docker:stable

services:
  - docker:dind

before_script:
  - echo "logging into dockerhub"
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - echo "login successfully"